// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import DisplayController from "./display_controller"
application.register("display", DisplayController)

import DisplaySecondQuestionController from "./display_second_question_controller"
application.register("display-second-question", DisplaySecondQuestionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
